"""Added notes col to UBC

Revision ID: 8c7c99ffbd5a
Revises: 
Create Date: 2023-12-19 14:14:41.243802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7c99ffbd5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book_connections', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
