"""Add rating to UBC

Revision ID: 924f96780a9e
Revises: dcfc6ba15b68
Create Date: 2023-12-22 22:22:32.126903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924f96780a9e'
down_revision = 'dcfc6ba15b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    with op.batch_alter_table('user_book_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book_connections', schema=None) as batch_op:
        batch_op.drop_column('rating')

    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fictionality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('library', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    # ### end Alembic commands ###
