"""Updates notes col: 100000 chars

Revision ID: cb1c9a068605
Revises: 8c7c99ffbd5a
Create Date: 2023-12-19 14:15:37.812043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1c9a068605'
down_revision = '8c7c99ffbd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book_connections', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book_connections', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
